### ISSUE TITLE
Assigning tasks to user groups

### ISSUE THREAD

**Issue by pr0l** [ozguryazilimas/redmine_default_assignee#1]
Hello, I liked your plugin. We need the tasks to be put not only on people, but also on groups. Could you tell me how to implement this with your plugin?

**Comment by zaburt** [comment]
I think this will require a code change, we will look into it

**Comment by zaburt** [comment]
Group support is added. If you enabled issue group assignment on Redmine settings you should see the groups on plugin configuration pages (project settings Default Assignee tab or Redmine plugin configuration page).

**Comment by zaburt** [comment]
Thank you for your report, group feature is in now so closing this issue
