### ISSUE TITLE
Feature - assign to the ticket autor. The real one.

### ISSUE THREAD

**Issue by kyvaith** [ozguryazilimas/redmine_default_assignee#13]
Hi,

Right now we have an option << author >> to be selected in your plugin, but it's more like a "Current User". I'd like to have an option to automatically assign Resolved tickets it's real authors (the author of the ticket). Can you add this feature?

Thanks in advance!
Tom.

**Comment by zaburt** [comment]
Hi Kyvaith,

As of version 1.2.1 we made a change so that selecting "author" means the issue author, and selecting "me" means current user. Does that not work for you ?

**Comment by kyvaith** [comment]
Sorry, didn't noticed that! Works perfectly! Thanks!

**Comment by zaburt** [comment]
Great, thank you ! closing the issue then
