### ISSUE TITLE
Error when accessing the settings of a project

### ISSUE THREAD

**Issue by tantic** [ozguryazilimas/redmine_default_assignee#2]
Hi,

first of all, thanks for this plugin which is very helpful.
I tried to install it on a new instance of Redmine this morning and i've got an error when i try to open the setting tab of a project.
Here is the log 

`ActionView::Template::Error (undefined method with_indifferent_access for #<RdaProjectSetting:0x007fc082fd7df8>):
    12:     <% IssueStatus.order(:position).each do |issue_status| %>
    13:       <p>
    14:         <%= content_tag :label, issue_status.name %>
    15:         <%= select_tag "settings[default_assignee][#{issue_status.id}]", principals_options_for_select(all_users, settings.with_indifferent_access[:default_assignee][issue_status.id.to_s]), :include_blank => true %>
    16:       </p>
    17:     <% end %>
    18:   </div>
  plugins/redmine_default_assignee/app/views/shared/_redmine_default_assignee_settings.erb:15:in block in _f611a6b95c175a98ae8e237fd423697a
  plugins/redmine_default_assignee/app/views/shared/_redmine_default_assignee_settings.erb:12:in _f611a6b95c175a98ae8e237fd423697a
  plugins/redmine_default_assignee/app/views/projects/_rda_project_settings.erb:11:in block in _3893b0c86629936764c222118fbb67a3
  plugins/redmine_default_assignee/app/views/projects/_rda_project_settings.erb:4:in _3893b0c86629936764c222118fbb67a3
  app/views/common/_tabs.html.erb:17:in block in _7f3b3458ee56e7d4933c860b5d96fbe2
  app/views/common/_tabs.html.erb:16:in each
  app/views/common/_tabs.html.erb:16:in _7f3b3458ee56e7d4933c860b5d96fbe2'
  app/helpers/application_helper.rb:345:in render_tabs
  app/views/projects/settings.html.erb:3:in _7f3ffab8f64fdcf346a5d4d89357707e
  lib/redmine/sudo_mode.rb:63:in sudo_mode
`

When i checkout an older commit, it works fine so I think it appeared in the last commit.
Thanks

**Comment by zaburt** [comment]
Yes the way with_indifferent_access is used is a recent change, we can workaround that if it is not supported on the environment. Which version of Ruby and Redmine are you using ?

**Comment by tantic** [comment]
Thanks for your reply

ruby 2.3.0p0
Redmine 3.4.6.stable

**Comment by zaburt** [comment]
Thank you for reporting the issue, this issue should be fixed now

**Comment by tantic** [comment]
It works indeed!! Thanks
