### ISSUE TITLE
error while accessing the settings page of project

### ISSUE THREAD

**Issue by skonac** [ozguryazilimas/redmine_default_assignee#5]
```
ActionView::Template::Error (super: no superclass method `project_settings_tabs' for #<#<Class:0x000055df562cab10>:0x00007fcd7c24ba20>
Did you mean?  project_issues_path):
    1: <h2><%=l(:label_settings)%></h2>
    2:
    3: <%= render_tabs project_settings_tabs %>
    4:
    5: <% html_title(l(:label_settings)) -%>
  plugins/redmine_dmsf/lib/redmine_dmsf/patches/projects_helper_patch.rb:29:in `project_settings_tabs'
  plugins/redmine_default_assignee/lib/redmine_default_assignee/patches/projects_helper_patch.rb:22:in `project_settings_tabs_with_redmine_default_assignee'
  plugins/redmine_dmsf/lib/redmine_dmsf/patches/projects_helper_patch.rb:29:in `project_settings_tabs'
  app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb___332217093551604048_70260315555960'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:68:in `call'
```

After installing plug-in, get this error when I want to access the projects settings page. I did the migrations.
My environment is below.

```
Environment:
  Redmine version                3.4.6.stable
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.5
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  redmine_default_assignee       0.6.0
  redmine_dmsf                   1.6.2
```

**Comment by zaburt** [comment]
Have you run the Redmine plugin migrations and restarted Redmine ?

    RAILS_ENV=production bundle exec rake redmine:plugins:migrate

**Comment by skonac** [comment]
Hi again,
Yes, i run the migrations and check the new table "rda_project_settings" in "redmine_production" database. After that i restart the apache, but still get the same error. After that i restart the server, but still get the same error.

**Comment by zaburt** [comment]
This looks like a bug in Redmine DMSF plugin. Adding this line to the top of redmine_dmsf/lib/redmine_dmsf/patches/projects_helper_patch.rb fixed the issue on my test environment, does it work for you too ?

```
require_dependency 'projects_helper'
```

**Comment by zaburt** [comment]
Nevermind the "require" change for DMSF mentioned above you don't need that. I have changed Redmine Default Assignee code to handle project settings in a different way, we are not doing method chaining anymore. Please try with the latest code.

**Comment by skonac** [comment]
Thank you. It is working now.
