### ISSUE TITLE
redmine3 branch

### ISSUE THREAD

**Issue by pauliusbau** [ozguryazilimas/redmine_default_assignee#7]
Hi.

I am using redmine 3.4 and would like to use your plugin. In the README.md there is a note, that:

> If you want to use it with Redmine 3.x please use redmine3 branch

Where is the "redmine3" branch? I am able to see only a master branch on your github.
Maybe I could use one of the releases instead?

**Comment by dfisek** [comment]
There seems to be a problem with our git mirroring (the repository on Github is actually a mirror of the repository in our local Gitlab server), it ignores the branches. We'll fix it.

**Comment by timucin** [comment]
I fixed the mirroring issue. Now redmine3 branch is here.
