### ISSUE TITLE
Tickets aren't removed from my tickets

### ISSUE THREAD

**Issue by zween27** [ozguryazilimas/redmine_default_assignee#8]
If a ticket is assigned to another person after state change via the default assignee plugin it doesn't disappear from the “my tickets” list. I have to open the ticket in edit mode and close it without any change to make it disappear from my list.

**Comment by zaburt** [comment]
The way this plugin works is, we configure the system and define a mapping that says "issue status X will be assigned to user Y". And then when we open the issue edit page, and change the issue status the assignee is changed according to the mapping we configured. This plugin does not modify the data (issue etc.) that is saved to the database, it only changes what is selected by default on the UI.

In the light of above, I could not understand how the plugin affects the scenario you mentioned as we are not changing the saved data in any way. I believe what you see is probably related to another plugin in your system or a configuration issue. If that is not the case can you give more details ?

**Comment by zween27** [comment]
Thanks for your fast reply, this explains the behavior in our system. 

If we just change the issues state in the list view the assigned person isn't changed and the issue is still assigned to me. As soon as I open it in edit mode the plugin takes effect and puts in the default person into assigned field and if I close the ticket the change takes effect and the issue disappears from my list. So, we should always open the issue in edit mode and don't change the state from the overview list.
