### ISSUE TITLE
Add Functions

### ISSUE THREAD

**Issue by openncomp** [ozguryazilimas/redmine_default_assignee#9]
It would be great if you added the ability to assign a task to the user who has set a particular status, rather than assigning it statically to one.
_____
Было бы замечательно, если бы вы добавили возможность назначения задачи тому пользователю, который установил тот или иной статус, а не назначать статически одному.

**Comment by zaburt** [comment]
Thank you for your comment. I could not understand what you are suggesting though, can you explain how the behavior would be ? A user having a status, is that a Redmine feature or do you have it by installing another plugin ? Normally Redmine user statuses are AFAIK active, registered, locked and they are set by admins, is this status something else ?

**Comment by openncomp** [comment]
Thanks for the answer!
I'll explain in more detail now.

I have the status of the task "IN progress".
There is an employee "John".
There are other employees 1, 2, 3, etc.

In your plugin, you can configure if one of the employees 1, 2, 3 sets the status "IN progress", then the task will automatically be assigned to the employee "John".
I propose to make sure that the task is assigned to the employee who set this status.
For example, employee 1 set the status "IN progress" and the task was automatically assigned to him.
Similar functionality is implemented in the "Additional" plugin:
https://github.com/alphanodes/additionals
But there it is implemented through setting the status in the sidebar, and not through the standard Redmine form, which is inconvenient.

If my English is bad, feel free to clarify.
___
Спасибо за ответ!
Сейчас объясню подробнее.

У меня есть статус задачи "В работе".
Есть сотрудник "Джон".
Есть другие сотрудники 1, 2, 3 и т.д.

В вашем плагине можно настроить, если кто-то из сотрудников 1, 2, 3 установит статус "В работе", то задача автоматически назначится сотруднику "Джон".
Я же предлагаю сделать так, чтобы задача назначалась тому сотруднику, кто установил этот статус.
Например, сотрудник 1 установил статус "В работе" и задача автоматически назначилась ему.
Подобный функционал реализован в плагине "Additionals":
https://github.com/alphanodes/additionals
Но там это реализовано через установку статуса в боковой панели, а не через стандартную форму Redmine, что неудобно.

Если мой английский плох, не стесняйтесь уточнить.

**Comment by zaburt** [comment]
Thank you for the explanation, I think I understand it now. When configuring the plugin, we can select which user will be assigned for a given issue status. In the assignable user list there is an option "<< me >>", if you select that, during updating of an issue "<< me >>" will translate into "who is changing the issue status". I think that is doing what you want. Is that good enough for you, or do you need something else ?

**Comment by openncomp** [comment]
Sorry for the long wait.
I will check this behavior again, but that's what I did, I set `<<me>>` in the plugin, created a task on behalf of another user that was not assigned to me. Then I went in and set the status "IN progress".
The task was assigned to me, but the value of my name was also set in the plugin settings.
___
Извините за долгое ожидание.
Я проверю данное поведение еще раз, но я так и делал, в плагине ставил << me >>, создавал от имени другого пользователя задачу, которая была назначена не мне. Потом заходил и ставил статус "В работе".
Задача назначалась мне, но в настройках плагина также выставлялось значение моего имени.

**Comment by zaburt** [comment]
Sorry you are right, "me" does not do that. I have added another option "author" which is for "who is updating the issue". Can you give it a try ?

**Comment by openncomp** [comment]
Of course, it will be interesting!
I will try to test it soon!
___
Конечно, это будет интересно!
В ближайшее время я постараюсь это протестировать!

**Comment by openncomp** [comment]
Hello.
I do not know what is going on, but the plugin does not change the assigned user when the status changes.
I've already removed all the other plugins, but it still doesn't happen.

My system:
```
Redmine version 4.2.2.stable
Ruby    version 2.6.6-p146
Rails   version 5.2.6
```
___
Здравствуйте.
Я не знаю, что происходит, но плагин не меняет назначенного пользователя при изменении статуса.
Я уже удалил все остальные плагины, но этого все равно не происходит.

Моя система:
```
Redmine version 4.2.2.stable
Ruby    version 2.6.6-p146
Rails   version 5.2.6
```

**Comment by openncomp** [comment]
I'm sorry, your plugin is working.
For it to work, I had to give the necessary rights in the roles and enable it in the project settings.
There is one more note, if I change the status of a task through the context menu in the task list, then the user is not assigned.
The assignment occurs only when I enter the task, click edit and change the status there.
Is it possible to make the user change when changing the status through the context menu (in the task list, right-click on the task and select the desired status).
___
Прошу прощения, ваш плагин работает.
Для его работы я должен был дать необходимые права в ролях и включить его в настройках проекта.
Еще есть одно замечание, если я меняю статус задачи через контекстное меню в списке задач, то пользователь не назначается.
Назначение происходит только тогда, когда я захожу в задачу, нажимаю редактировать и там меняю статус.
Можно ли сделать, чтобы пользователь менялся при смене статуса через контекстное меню (в списке задач нажимаем правой кнопкой на задаче и выбираем необходимый статус).

**Comment by openncomp** [comment]
For statistics.
Your plugin also works great without conflicts with such a set of plugins:
```
Redmine plugins:
  a_common_libs                  2.5.7
  additional_tags                1.0.2
  additionals                    3.0.3
  nxs_chat                       2.0
  redmine_agile                  1.6.2
  redmine_base_deface            1.5.3
  redmine_checklists             3.1.19
  redmine_cms                    1.2.2
  redmine_contacts               4.3.4
  redmine_default_assignee       1.1.0
  redmine_dmsf                   2.4.8
  redmine_drawio                 1.1.4
  redmine_hide_estimated_hours   1.0.14
  redmine_impersonate            2.0.0
  redmine_incoming_emails        0.0.1
  redmine_issue_dynamic_edit     0.7.2
  redmine_mentions               0.0.1
  redmine_more_previews          2.0.7
  redmine_priorities_duedate_js  0.1.0
  redmine_questions              1.0.2
  redmine_shortcuts              0.5.1
  redmine_silencer               0.4.3
  redmine_theme_changer          0.4.0
  sidebar_hide                   0.0.8
  that_email_log                 0.0.4
  that_issue_reply_button        0.0.1
  unread_issues                  2.2.4
  vault                          0.4.3
```
__
Для статистики.
Ваш плагин также прекрасно работает без конфликтов с таким набором плагинов:

**Comment by zaburt** [comment]
As of version 1.2.0 if the setting "Apply on Context Menu" is selected, the assigned users are changed based on plugin settings. The users can not be changed on the UI because as soon as a selection is done it is send to server, so on the server side if there is an issue status change request received, we apply plugin settings.
